import java.util.*;

public class P029DistinctPowers {
  private static TreeSet<Double> set = new TreeSet<Double>();
  public static void main(String[] args) {
    for (int a = 2; a <= 100; a++ ) {
      for (int b = 2; b <= 100; b++ ) {
        set.add(Math.pow(a, b));
      }
    }
    System.out.println("Distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is " + set.size());
  }
}
