// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
// Find the next triangle number that is also pentagonal and hexagonal.
import java.lang.*;

public class P045TriangularPentagonalAndHexagonal {

  private static boolean isPentagonal(long number) {
    if (number <= 0)
			return false;

    double penTest = (Math.sqrt(1 + 24 * number) + 1.0) / 6.0;
    return penTest == ((int)penTest);
  }

  private static boolean isHexagonal(int number) {
    double hexTest = (Math.sqrt(1 + 8 * number) + 1.0) / 4.0;
    return hexTest == ((int)hexTest);
  }

  private static int getTriangle(int number) {
    return (int) ((number * number + 1) / 2);
  }

  public static void main(String[] args) {
    int number = 286;
    while(true) {
      int triangle = getTriangle(number);
      if(isPentagonal(number) && isHexagonal(number)) {
        break;
      }
      number++;
    }
    System.out.format("The next triangle number after 40755 that's also pentagonal and hexagonal is %d.%n", getTriangle(number));
  }
}
